version: "3.8"

services:
  fastapi-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./media:/app/media
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 8080 --reload  
    environment:
      - PYTHONUNBUFFERED=1  